### ISSUE TITLE
Please identify a license

### ISSUE THREAD

**Issue by xarses** [Derimagia/ForgeSlack#2]
Please add a LICENCE file or the like. Without one, your code while posted publicly, may not be copied, modified, distributed, or used. If you aren't sure which license to apply, please see helpful sites like http://choosealicense.com/

**Comment by derimagia** [comment]
Thanks for pushing me to do this, was slacking on it! MIT license

**Comment by xarses** [comment]
Thanks, this is the only one that we could get working with forge in 1.7.10 and it's super awesome to have.

**Comment by derimagia** [comment]
Yeah totally - that's why I built it. was using the IRC gateway before but it was subpar so I went to make this. Let me know if you have any suggestions
