### ISSUE TITLE
1.10.2 branch - Slack API not connecting

### ISSUE THREAD

**Issue by zedle** [Derimagia/ForgeSlack#3]
So I compiled the 1.10.2 branch against the latest APIs (updated the dep for the Slack API too) and it seems to never connect to Slack despite the bot token being correct - confirmed it was getting the token as well. Server just dies after it tries to send the first message to slack.

Any idea what's going on here? It'd be great to have this working for my company's server.

**Comment by derimagia** [comment]
It looks like I had a commit that I never pushed up - I only used that version on 1 server. 

It was a fix for shading and I remember that was giving me some headaches but I did get it working, can you try to build it now?

Here's the commit:
https://github.com/derimagia/ForgeSlack/commit/2605cfafa11d25e4a2b0514c2a4fc8d78cfaa356

**Comment by zedle** [comment]
That did the trick. Thanks!
